Repository Green-Software-Foundation/patterns, pull requests merged in 2023-10, with the labels that each got.

#256 Update docusaurus.config.js
  docusaurus.config.js
Labels: bug

#262 Merge 'main' back into 'dev' so the branches are in sync
  .github/ISSUE_TEMPLATE/meeting-template.md
  README.md
  docs/catalog/ai/index.md
  docs/catalog/cloud/index.md
  docs/catalog/cloud/scale-kubernetes-workloads-based-on-events.md
  docs/catalog/cloud/use-circuit-breaker.md
  docs/guide/index.md
  docs/index.mdx
  docusaurus.config.js
  static/img/og-image.png
Labels: bug

#221 Evaluate other CPU architectures
  docs/catalog/cloud/evaluate-other-cpu-architectures.md
Labels: proposed pattern, CLOUD, Technical Writer Review, Ready to Merge

#219 Use server-side rendering for high-traffic pages
  docs/catalog/web/use-server-side-rendering.md
Labels: proposed pattern, WEB, Ready to Merge

#209 Use Asynchronous Calls instead of sync when doing Network calls #76
  docs/catalog/cloud/use-async-instead-of-sync.md
Labels: proposed pattern, CLOUD, Ready to Merge

#273 Update evaluate-other-cpu-architectures.md
  docs/catalog/cloud/evaluate-other-cpu-architectures.md
Labels: Technical Writer Review, Ready to Merge

#272 Update use-async-instead-of-sync.md
  docs/catalog/cloud/use-async-instead-of-sync.md
Labels: Technical Writer Review, Ready to Merge

#271 Update enable-text-compression.md
  docs/catalog/web/enable-text-compression.md
Labels: Technical Writer Review, Ready to Merge

#270 Update keep-request-counts-low.md
  docs/catalog/web/keep-request-counts-low.md
Labels: Technical Writer Review, Ready to Merge

#268 Update use-server-side-rendering.md
  docs/catalog/web/use-server-side-rendering.md
Labels: Technical Writer Review, Ready to Merge
